# Generated by Django 3.0.7 on 2020-08-14 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=30)),
                ('income', models.DecimalField(decimal_places=2, max_digits=30)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=30)),
                ('company_goal', models.CharField(choices=[('1', 'Invest in new machines, development or other'), ('2', 'Grow the size of employees, location or other'), ('3', 'Make a turn around to save the company'), ('4', 'Get Investment')], default=2, max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
