# Generated by Django 3.0.7 on 2020-08-07 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_logo', models.ImageField(blank=True, upload_to='dashboard/logos')),
                ('co_nip_number', models.CharField(max_length=10)),
                ('co_name', models.CharField(max_length=60)),
                ('co_address', models.CharField(max_length=100)),
                ('co_zip', models.CharField(max_length=10)),
                ('co_city', models.CharField(max_length=30)),
                ('co_country', models.CharField(max_length=50)),
                ('co_telephone', models.CharField(max_length=20)),
                ('co_email', models.CharField(max_length=50)),
                ('co_website', models.CharField(max_length=35)),
                ('co_att_person', models.CharField(max_length=60)),
                ('co_ean_number', models.CharField(max_length=30)),
                ('co_payment_method', models.CharField(choices=[('IP', 'Invoice Paid'), ('RM', 'Recurring Monthly'), ('NE', 'Netto'), ('NC', 'Netto Cash')], default='NE', max_length=2)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(blank=True, default=1, null=True)),
                ('place', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_sent', models.DateTimeField(auto_now=True, verbose_name='date sent by mail')),
                ('date_deadline', models.DateTimeField(verbose_name='payment deadline')),
                ('bank_number', models.CharField(max_length=40)),
                ('iban_number', models.CharField(max_length=40)),
                ('swift_bic', models.CharField(max_length=40)),
                ('total', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=40)),
                ('paid_status', models.BooleanField(default=False)),
                ('custom_comment', models.CharField(max_length=40)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BusinessContact')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('invoice_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=8)),
                ('vat_rule', models.CharField(choices=[('0.00', '0%'), ('0.05', '5%'), ('0.08', '8%'), ('0.23', '23%')], default='0.23', max_length=4)),
                ('unit', models.CharField(choices=[('1', 'Days'), ('2', 'Deliveries'), ('3', 'Cartons'), ('4', 'Boxes'), ('5', 'Kilograms'), ('6', 'Kilometers'), ('7', 'Cubic Meter'), ('8', 'Square Meters'), ('9', 'Liters'), ('10', 'Months'), ('11', 'Meters'), ('12', 'Packages'), ('13', 'Sessions'), ('14', 'Pieces'), ('15', 'Sets'), ('16', 'Hours'), ('17', 'Weeks')], default=16, max_length=2)),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('bought_from', django_countries.fields.CountryField(max_length=2)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('vat_rule', models.CharField(choices=[('0.00', '0%'), ('0.05', '5%'), ('0.08', '8%'), ('0.23', '23%')], default='0.23', max_length=4)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
