# Generated by Django 3.0.7 on 2020-08-07 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesToPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('bought_from', django_countries.fields.CountryField(max_length=2)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('vat_rule', models.CharField(choices=[('0.00', '0%'), ('0.05', '5%'), ('0.08', '8%'), ('0.23', '23%')], default='0.23', max_length=4)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BusinessContact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
