# Generated by Django 3.0.7 on 2020-08-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200812_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceQuantity',
        ),
    ]
