# Generated by Django 3.0.7 on 2020-08-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200818_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensestopay',
            name='price',
        ),
    ]
