# Generated by Django 3.0.7 on 2020-08-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_expensestopay_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestopay',
            name='price',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
