# Generated by Django 3.1 on 2020-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200822_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payment deadline'),
        ),
    ]
