# Generated by Django 3.1 on 2020-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200827_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensespaid',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expensestopay',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
