# Generated by Django 3.1 on 2020-08-31 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20200828_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessContact',
            new_name='Client',
        ),
    ]
