# Generated by Django 3.1 on 2020-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200831_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='co_ean_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='co_logo',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/logos'),
        ),
    ]
