# Generated by Django 3.0.7 on 2020-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_co_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('da', 'Danish'), ('se', 'Swedish'), ('no', 'Norwegian')], default='en', max_length=2),
        ),
    ]
