# Generated by Django 3.1 on 2020-08-19 17:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200819_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='lol'),
            preserve_default=False,
        ),
    ]
